metadata:
  name: remote-worklfow-node-selector
spec:
  desired_state: online
  functions:
  - url: func.py
    name: my-func-allow
    kind: job
    image: mlrun/mlrun
    handler: func_allow
  - url: func.py
    name: my-func-prevent
    kind: job
    image: mlrun/mlrun
    handler: func_prevent
  - url: func.py
    name: my-func-constrain
    kind: job
    image: mlrun/mlrun
    handler: func_constrain
  workflows:
  - path: my_workflow.py
    name: my_workflow
  source: ''
  conda: ''
  default_function_node_selector:
    app.iguazio.com/node-group: added-wr17wzokx4
kind: project
